### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b = np.array([[1,2,3,],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#dtype
np.array([1,2,0], dtype=float)

array([1., 2., 0.])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.random.random((3,4))

array([[0.97713084, 0.71175764, 0.62469718, 0.94915427],
       [0.09426592, 0.07203142, 0.17478176, 0.44013806],
       [0.84299942, 0.29257858, 0.89290793, 0.36400237]])

In [20]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [24]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
# ndim
a3.ndim

3

In [31]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
# size
a3.size

8

In [37]:
# itemsize
print(a1.itemsize)

8


In [38]:
#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype

In [44]:
#astype

print(a3.astype(np.int32))
print(a3.itemsize)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
8


### Array Operations

In [45]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
# scalar operations
#arithmetic

a2 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [53]:
# relational

a2**2 ==529

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [55]:
# vector operations
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Numpy functions

In [56]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[63., 39., 78.],
       [ 9., 62.,  1.],
       [76., 77., 33.]])

In [63]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1, axis=0)

array([76., 77., 78.])

In [68]:
# mean/median/std/var
np.var(a1, axis=1)

array([258.        , 732.66666667, 420.66666667])

In [69]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.1673557 ,  0.96379539,  0.51397846],
       [ 0.41211849, -0.7391807 ,  0.84147098],
       [ 0.56610764,  0.99952016,  0.99991186]])

In [70]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [73]:
# log and exponents
np.exp(a1)

array([[2.29378316e+27, 8.65934004e+16, 7.49841700e+33],
       [8.10308393e+03, 8.43835667e+26, 2.71828183e+00],
       [1.01480039e+33, 2.75851345e+33, 2.14643580e+14]])

In [77]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[45., 27., 78.],
       [68.,  7., 91.]])

### Indexing and Slicing

In [78]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a2[1,0]

4

In [86]:
a3[0,1,0]

2

In [87]:
a3[1,0,1]

5

In [88]:
a3[0,0,0]

0

In [90]:
a3[1,1,0]

6

In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a1[2:5:2]

array([2, 4])

In [96]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a2[0,:]

array([0, 1, 2, 3])

In [98]:
a2[:,2]

array([ 2,  6, 10])

In [100]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [101]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [102]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [104]:
a2[1,::3]

array([4, 7])

In [108]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [110]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
a3[1,:,1]

array([10, 13, 16])

In [118]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [121]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [127]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [123]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [124]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [137]:
# Transpose
a2.T
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [140]:
# ravel
# converts any dimension array into one dimension
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [141]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [142]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [143]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [144]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [146]:
# vertical splitting

In [147]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [151]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]