### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[39, 24, 18, 28],
       [74, 85, 33, 49],
       [93, 53, 49, 13],
       [50, 31, 46, 27],
       [ 4, 66,  2,  3],
       [46, 62, 19, 30]])

In [3]:
np.sort(a)[::-1]

array([99, 92, 85, 71, 64, 50, 46, 38, 36, 23, 16, 12, 10,  2,  2])

In [4]:
np.sort(b, axis=0)

array([[ 4, 24,  2,  3],
       [39, 31, 18, 13],
       [46, 53, 19, 27],
       [50, 62, 33, 28],
       [74, 66, 46, 30],
       [93, 85, 49, 49]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
np.append(a,200)

array([  2,  16,  46,  12,  38,  64,  50,  23,  36,  99,  85,  92,   2,
        10,  71, 200])

In [6]:
b

array([[39, 24, 18, 28],
       [74, 85, 33, 49],
       [93, 53, 49, 13],
       [50, 31, 46, 27],
       [ 4, 66,  2,  3],
       [46, 62, 19, 30]])

In [7]:
np.append(b,np.ones((b.shape[0],1)), axis =1)

array([[39., 24., 18., 28.,  1.],
       [74., 85., 33., 49.,  1.],
       [93., 53., 49., 13.,  1.],
       [50., 31., 46., 27.,  1.],
       [ 4., 66.,  2.,  3.,  1.],
       [46., 62., 19., 30.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
a.shape

(15,)

In [14]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a, axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 5,  9, 10, 11, 14]),)

In [18]:
# repace all values > 50 with 0
np.where(a>50,0,a)

array([ 2, 16, 46, 12, 38,  0, 50, 23, 36,  0,  0,  0,  2, 10,  0])

In [19]:
# replace all even numbers with 0
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0,  0,  0,  0, 23,  0, 99, 85,  0,  0,  0, 71])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [21]:
np.argmax(a)

9

In [22]:
b

array([[39, 24, 18, 28],
       [74, 85, 33, 49],
       [93, 53, 49, 13],
       [50, 31, 46, 27],
       [ 4, 66,  2,  3],
       [46, 62, 19, 30]])

In [23]:
np.argmax(b,axis=0)

array([2, 1, 2, 1])

In [24]:
np.argmax(b,axis=1)

array([0, 1, 0, 0, 1, 1])

In [25]:
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [27]:
np.cumsum(a)

array([  2,  18,  64,  76, 114, 178, 228, 251, 287, 386, 471, 563, 565,
       575, 646])

In [28]:
b

array([[39, 24, 18, 28],
       [74, 85, 33, 49],
       [93, 53, 49, 13],
       [50, 31, 46, 27],
       [ 4, 66,  2,  3],
       [46, 62, 19, 30]])

In [29]:
np.cumsum(b)

array([ 39,  63,  81, 109, 183, 268, 301, 350, 443, 496, 545, 558, 608,
       639, 685, 712, 716, 782, 784, 787, 833, 895, 914, 944])

In [31]:
np.cumsum(b, axis=1)

array([[ 39,  63,  81, 109],
       [ 74, 159, 192, 241],
       [ 93, 146, 195, 208],
       [ 50,  81, 127, 154],
       [  4,  70,  72,  75],
       [ 46, 108, 127, 157]])

In [32]:
# np.cumprod
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [33]:
np.cumprod(a)

array([                  2,                  32,                1472,
                     17664,              671232,            42958848,
                2147942400,         49402675200,       1778496307200,
           176071134412800,   14966046425088000, 1376876271108096000,
       2753752542216192000, 9090781348452368384, -190566839716151296])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [34]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [37]:
np.percentile(a,50)

38.0

In [38]:
np.median(a)

38.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [39]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [41]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [42]:
salary =([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [43]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [45]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([50, 10])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [46]:
a

array([ 2, 16, 46, 12, 38, 64, 50, 23, 36, 99, 85, 92,  2, 10, 71])

In [47]:
np.flip(a)

array([71, 10,  2, 92, 85, 99, 36, 23, 50, 64, 38, 12, 46, 16,  2])

In [48]:
b

array([[39, 24, 18, 28],
       [74, 85, 33, 49],
       [93, 53, 49, 13],
       [50, 31, 46, 27],
       [ 4, 66,  2,  3],
       [46, 62, 19, 30]])

In [49]:
np.flip(b)

array([[30, 19, 62, 46],
       [ 3,  2, 66,  4],
       [27, 46, 31, 50],
       [13, 49, 53, 93],
       [49, 33, 85, 74],
       [28, 18, 24, 39]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [52]:
a

array([110, 530,  46,  12,  38,  64,  50,  23,  36,  99,  85,  92,   2,
        10,  71])

In [51]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [53]:
a

array([110, 530,  46,  12,  38,  64,  50,  23,  36,  99,  85,  92,   2,
        10,  71])

In [56]:
np.delete(a,[0,2,4])

array([530,  12,  64,  50,  23,  36,  99,  85,  92,   2,  10,  71])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [57]:
m = np.array([1,2,3,4,5])
n= np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.intersect1d(m,n)

array([3, 4, 5])

In [60]:
np.setdiff1d(m,n)

array([1, 2])

In [61]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [62]:
np.in1d(m,1)

array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [63]:
a

array([110, 530,  46,  12,  38,  64,  50,  23,  36,  99,  85,  92,   2,
        10,  71])

In [64]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 46, 25, 38, 64, 50, 25, 36, 75, 75, 75, 25, 25, 71])

In [ ]:
# 17. np.swapaxes